name: Deploy to Droplet

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Optional local step; works even without package-lock.json
      - name: Install deps locally (optional build)
        run: npm install --no-audit --no-fund

      # Make sure the folder exists on the Droplet
      - name: Create app dir on server (if missing)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/deploy/apps/mastermind-bet

      # Sync repo to server via rsync (requires rsync installed server-side)
      - name: Upload files to server (rsync)
        uses: easingthemes/ssh-deploy@v4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rtlDz --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "/home/deploy/apps/mastermind-bet"

      # Install on server & (re)start with PM2
      - name: Install deps on server & restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/deploy/apps/mastermind-bet
            npm install --omit=dev --no-audit --no-fund
            pm2 start index.js --name mastermind-bet || pm2 reload mastermind-bet
            pm2 save
