name: Deploy to Droplet
on:
push:
branches: [ main ]
jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Start ssh-agent
uses: webfactory/ssh-agent@v0.9.0
with:
ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
- name: Refresh known_hosts
run: |
ssh-keygen -R ${{ secrets.DO_SSH_HOST }} || true
mkdir -p ~/.ssh
ssh-keyscan -H ${{ secrets.DO_SSH_HOST }} >> ~/.ssh/known_hosts
- name: Rsync files
run: |
rsync -avz --delete --exclude='.git' ./ ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }}:/opt/mastermind-bet/
- name: Install deps & restart
run: |
ssh ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_HOST }} \
'cd /opt/mastermind-bet && npm ci || npm i && sudo systemctl restart mastermind-bet'
